/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 .\public\prototype\prototype.gltf
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import {useFrame} from '@react-three/fiber';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("prototype/prototype.gltf");
  const { actions } = useAnimations(animations, group);

  useFrame((state, delta) => (group.current.rotation.y += delta))

  return (
    <group ref={group} {...props} dispose={null} scale={50}>
      <group name="Scene">
        <group
          name="NurbsPath"
          position={[0.01, 0.31, -0.36]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.11}
        />
        <group
          name="NurbsPath001"
          position={[0.01, 0.31, -0.36]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.11}
        />

        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.9}
          position={[1.46, 0.43, 2.15]}
          rotation={[-0.84, 1.35, 0.82]}
        />
        <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.SY_basic_black_rubber}
            material-color={"red"}
        />
        <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={materials.SY_basic_black_rubber}
            position={[-1, 1, 0]}
            rotation={[0, 0, Math.PI / 2]}
            material-color={"#3178eb"}
        />
        <group name="Cylinder" position={[0, 0.41, -0.08]} scale={0.01}>
          <mesh
            name="Cylinder_1"
            geometry={nodes.Cylinder_1.geometry}
            material={materials["ME_BRUSHED METAL"]}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_2"
            geometry={nodes.Cylinder_2.geometry}
            material={materials["Material.003"]}
            
          />
          <mesh
            name="Cylinder_3"
            geometry={nodes.Cylinder_3.geometry}
            material={materials["ME_Uber_[bcmp] Gold_G"]}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_4"
            geometry={nodes.Cylinder_4.geometry}
            material={materials.SY_basic_plastic_white}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_5"
            geometry={nodes.Cylinder_5.geometry}
            material={materials["SY_Uber_[bcmp] MattPlastic_G.001"]}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_6"
            geometry={nodes.Cylinder_6.geometry}
            material={materials.ME_jewelry_gold_G}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_7"
            geometry={nodes.Cylinder_7.geometry}
            material={materials.CP_PaintFinish_Matte_Flat}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_8"
            geometry={nodes.Cylinder_8.geometry}
            material={materials.GL_Glowing_Crystal_G}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_9"
            geometry={nodes.Cylinder_9.geometry}
            material={materials["AB_herbe 2"]}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_10"
            geometry={nodes.Cylinder_10.geometry}
            material={materials.GL_reflective_G}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_11"
            geometry={nodes.Cylinder_11.geometry}
            material={materials["SY_Uber_[bcmp] Matt_G"]}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_12"
            geometry={nodes.Cylinder_12.geometry}
            material={materials.SY_basic_plastique}
            material-color={"gray"}
          />
          <mesh
            name="Cylinder_13"
            geometry={nodes.Cylinder_13.geometry}
            material={materials["Material.001"]}
            material-color={"gray"}
          />
        </group>
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials.SY_basic_black_rubber}
          position={[0, 1, -1]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          
        />
      </group>
    </group>
  );
}

useGLTF.preload("prototype/prototype.gltf");
